// !!! Do not modify this file !!!
// This file is used to prevent typescript compiling failure.
// The real content will be dynamically generated by the compiling script.
import "/views/app-main/app-main.m.js";

const view_content:{[key:string]:string} = {};
export default view_content;